### ISSUE TITLE
Must be hosted on https

### ISSUE THREAD

**Issue by mattburman** [juliosantos/swarmacarta#1]
Currently experimenting with hosting my own version of this application :-).

The example does not work presumably because of the following
```
main.js:92 getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
getUserLocation @ main.js:92
```

**Comment by mattburman** [comment]
When hosting my own on https, getting my own foursquare app client_id, and getting my own Google Maps API key, it works :-)

**Comment by juliosantos** [comment]
@mattburman Yep: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
